# Generated by Django 4.2.2 on 2023-07-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ingredienttorecipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredienttorecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientToRecipe',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
