GET http://127.0.0.1:8000/api/users/
page:1
limit:6
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
"email": "sefsefgr@yandex.ru",
"username": "dfswekjdgr.pupkin",
"first_name": "ИИся",
"last_name": "ИИпкин",
"password": "tretuh567"
}
###
GET http://127.0.0.1:8000/api/users/1/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
GET http://127.0.0.1:8000/api/users/me/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
POST http://127.0.0.1:8000/api/users/set_password/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
Content-Type: application/json

{
"new_password": "string123",
"current_password": "tretuh567"
}
###
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
"password": "123",
"email": "fjfj@ya.ru"
}
###
POST http://127.0.0.1:8000/api/auth/token/logout/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
GET http://127.0.0.1:8000/api/tags/
###
GET http://127.0.0.1:8000/api/tags/1/
###
GET http://127.0.0.1:8000/api/recipes/
page:
limit:
is_favorited:
is_in_shopping_cart:
author:
tags:
###
POST  http://127.0.0.1:8000/api/recipes/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
Content-Type: application/json

{
"ingredients": [
    {
      "id": 6,
      "quantity": 5
    }
  ],
"tags": [
1
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"title": "Новенький",
"text": "ИТАЛГОРУАш",
"cooking_time": 20
}
###
GET http://127.0.0.1:8000/api/recipes/2/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
PATCH http://127.0.0.1:8000/api/recipes/16/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
Content-Type: application/json

{
"ingredients": [
{}
],
"tags": [
1
],
"image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
"name": "string",
"text": "string",
"cooking_time": 1
}
###
DELETE http://127.0.0.1:8000/api/recipes/16/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
POST http://127.0.0.1:8000/api/recipes/2/shopping_cart/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
DELETE http://127.0.0.1:8000/api/recipes/15/shopping_cart/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
GET http://127.0.0.1:8000/api/ingredients/
?title=Сосиски
###
GET  http://127.0.0.1:8000/api/ingredients/3/
###
POST http://127.0.0.1:8000/api/recipes/2/favorite/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
DELETE http://127.0.0.1:8000/api/recipes/2/favorite/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
GET  http://127.0.0.1:8000/api/users/subscriptions/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
page:1
limit:6
recipes_limit:2
###
POST http://127.0.0.1:8000/api/users/1/subscribe/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
recipes_limit:1
###
DELETE  http://127.0.0.1:8000/api/users/1/subscribe/
Authorization: Token 57960441f86ee308f0fb0064c0de259c1af6cc0b
###
Token c831074c99182afe2fae3a9f991837cc28a3e747

